[versions]
kotlin-version = "2.1.10"
ktor-version = "3.0.3"
fb-admin-version = "9.4.3"
mockk-version = "1.12.0"
logback-version = "1.4.14"

[libraries]
firebase-admin = { module = "com.google.firebase:firebase-admin", version.ref = "fb-admin-version" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor-version" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor-version" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin-version" }
mockk-test = { module = "io.mockk:mockk", version.ref = "mockk-version" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }